### ISSUE TITLE
Design Profile page

### ISSUE THREAD

**Issue by suninthesky** [thisisfieldworks/platform#11]
States: complete, incomplete

**Comment by chris-fw** [comment]
@suninthesky if possible i was thinking how we could make the mock up slightly more tailored to the group fede is meeting.  Just to make it a little more real.

 - Donor Logos - 
![logo_stars_foundation](https://user-images.githubusercontent.com/31283578/30795678-9764b7d2-a1c6-11e7-8368-083e37bb6344.jpg)
![thousandcurrents](https://user-images.githubusercontent.com/31283578/30795680-97674416-a1c6-11e7-96a8-1599e0017081.jpg)
![wkkf_logo 770x5778_revised](https://user-images.githubusercontent.com/31283578/30795679-9766f222-a1c6-11e7-9d18-b66f7e5cf658.jpg)

 - Recommended by
![chris profile 1](https://user-images.githubusercontent.com/31283578/30795698-acd0d114-a1c6-11e7-92be-8e0ba01e364d.jpg)
![richard-branson-3](https://user-images.githubusercontent.com/31283578/30795739-dba30ae8-a1c6-11e7-9d1f-6d14e3452639.jpg)

**Comment by chris-fw** [comment]
**programme summary**: 
Starburst implements a defined 2 year programme in each of its communities which begins with an empowerment & capacity building approach and develops into water and sanitation infrastructure construction. Communities are selected in discussion with the community development councils as well as municipal authorities up to the Mayor.  These are then validated through analysis of the malnutrition rate of infants (0-2 years of age) and a community’s access to clean water. Their holistic programme is narrowly focussed on addressing the factors that contribute to infant malnourishment figures. 

**activity summary**
Activities are centred around the creation of women and youth ‘self-help’ groups from which their community promoters are selected and trained. Every group receives monthly trainings on topics varying from healthy family nutrition and infant care (women’s groups) to leadership and engagement (youth groups). The community development council is similarly is mobilised to discuss the water and sanitation issues within the community and begin working with technicians from the Municipality to develop the plans for the installation of a water distribution system. 

**Copy Funding Concept Summary :** 
Starburst is looking to implement drip feed irrigation systems to complement their existing home allotment programme and expand their programme to provide safe and efficient water distribution.   The community has piloted and requested to install drip-feed irrigation systems.  This would increase household income by 30% and reduce malnutrition rates by a further 17%.
While the current water programme allows some households to continue irrigating home gardens near their house all year round, 65% of households lack of opportunity to continue growing vegetables during the winter dry-season because it is too far to transport the water.

**Comment by suninthesky** [comment]
[Here](https://xd.adobe.com/view/ca5e8959-f7fc-4277-ba9a-50385f091ecf/) you go.
